
service: karponomicon
tenant: mflamb
app: karpo-service
provider:
  name: aws
  runtime: nodejs12.x
  profile: ${opt:profile, "karpo"}
  region: ${opt:region, self:custom.secrets.REGION}
  stage: ${opt:stage, "dev"}

  environment:
    TWILIO_ACCOUNT_SID: ${self:custom.secrets.TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${self:custom.secrets.TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${self:custom.secrets.TWILIO_PHONE_NUMBER}
    RECEIVER: ${self:custom.secrets.RECEIVER}

custom:
  secrets: ${file(secrets.${self:provider.stage}.json)}

# package:
#   exclude:
#     - "node_modules/**"
#     - "!node_modules/twilio/**"

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post
          integration: lambda
          cors: true
